### ISSUE TITLE
Homepage/ Poker page

### ISSUE THREAD

**Issue by Klas-Norling** [Klas-Norling/Pokersite#3]
# [Homepage]
A homepage or the page where the user can play poker

## Task description
The user can connect to a poker game, the users money that is saved in the database is used to bet with. Depending on placement in the poker game the corresponding amount of money is sent to their account (database). The page should not refresh when visual changes are made in the poker game. Other people should be able to connect to that game.

## Poker game
The visuals are made with html and css and the poker table, card deck and the cards can be images imported in the html code.
The entire deck can be represented in javascript with an array containing each card and then randomly picking an index of the array when presenting the 5 first cards. 

## Task checklist
- [ ] Frontend should be dynamic (HTML/HTMX, css, javascript) 
- [ ] Queries (Python/Flask, MySQL)
- [ ] Pokergame (Javascript, Python?)

## Task Completion test
[Task completion test, same as sprint story,maybe some pseudo code or a link to ci test]
